/**
 * @file Detection of HyperIDE's synthetic preview entry files.
 *
 * Accessed via: iframe-interaction.ts source resolvers (extension) and SaaS ElementTracer.
 * Assumptions: synthetic preview files are generated by lib/preview-generator and
 * always carry one of the fixed basenames below, regardless of the project's
 * source directory layout.
 *
 * The preview entry (`__canvas_preview__.tsx`) renders the selected user component
 * via a registry/sample map. It is NOT a go-to-code target: a clicked element must
 * resolve to its real component source, never to the synthetic wrapper. Source-map
 * resolution can collapse a compiled position back to this entry (it is the module
 * that imports and renders everything); callers must skip such resolutions and fall
 * back to the element's own fiber source.
 */

import type { SourceLocation } from './types';

/** Basenames of the synthetic preview entry files generated by lib/preview-generator. */
const SYNTHETIC_PREVIEW_BASENAMES = ['__canvas_preview__.tsx', '__canvas_preview_standalone__.tsx'];

/**
 * Returns true when the given path points at a synthetic preview entry file.
 * Matches on basename so it works for any directory layout and path separator,
 * and for both forward- and back-slash paths.
 */
export function isSyntheticPreviewPath(fileName: string | null | undefined): boolean {
  if (!fileName) return false;
  // Strip query strings (Vite HMR `?t=...`) before extracting the basename.
  const noQuery = fileName.split('?')[0];
  const basename = noQuery.split(/[/\\]/).pop() ?? noQuery;
  return SYNTHETIC_PREVIEW_BASENAMES.includes(basename);
}

/**
 * Per-frame selection shared by the server source-map resolvers in
 * iframe-interaction.ts (`resolveOwnServerSourceMap` and `resolveViaServerSourceMap`).
 *
 * Given the already-looked-up server-source-map cache values for one fiber's chunk
 * frames, in stack order, pick the first usable result and enforce the
 * synthetic-preview skip on EVERY path (sync direct + async RSC/pending-click
 * fallback). Cache value semantics:
 *  - `undefined` → warm-up still in flight: skip, try the next frame.
 *  - synthetic preview location → never a go-to-code target: skip, try the next
 *    frame (caller then falls back to the element's own fiber source).
 *  - `null` → warmed but genuinely unresolvable: stop, return `null`.
 *  - any other `SourceLocation` → resolved user source: return it.
 *
 * Returns `{ found: false }` when no frame yields a usable result (all in-flight or
 * synthetic) so the chain-walking caller can continue up the return chain.
 *
 * This keeps fiber internals out of `shared/` (the caller does the cache lookups and
 * the `fiber.return` walk) while making the synthetic-skip decision unit-testable.
 */
export type CachedFrameLocation = SourceLocation | null | undefined;

export function selectNonSyntheticCachedLocation(
  frames: readonly CachedFrameLocation[],
): { found: true; value: SourceLocation | null } | { found: false } {
  for (const cached of frames) {
    if (cached === undefined) continue; // warm-up still in flight — try next frame
    // The synthetic preview entry is never a valid go-to-code target — skip it so
    // resolution falls through to the next frame / the element's own fiber source.
    if (cached && isSyntheticPreviewPath(cached.fileName)) continue;
    return { found: true, value: cached };
  }
  return { found: false };
}
